version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mynetwork

  golang_app:
    build: .
    container_name: golang_app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mongodb_data:

